apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: config-service
build:
  artifacts:
    - image: ernestoacostacuba/config-service
      jib:
        args:
          - -Pjib
          - -DskipTests=true
  tagPolicy:
    gitCommit: {
      variant: AbbrevTreeSha,
      ignoreChanges: true
    }

  local:
    push: false

deploy:
  kubectl:
    manifests:
      - k8s/deployment.yml
