server:
  port: 8888
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: config-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    config:
      server:
        git:
          uri: https://github.com/springcloudnative/config-repo
          default-label: main
          timeout: 5            # Time limit to establish a connection with the remote repository
          clone-on-start: true  # Clones the remote repository locally on startup
          force-pull: true      # Forces pulling the remote repository and discarding any local change

